services:
  graphdb:
    image: ontotext/graphdb:10.8.0
    ports:
      - "7200:7200"
    environment:
      GDB_JAVA_OPTS: "-Dgraphdb.workbench.importDirectory=/opt/graphdb/home/graphdb-import"
    volumes:
      - type: bind
        source: ./search/WeVerify-config.ttl
        target: /opt/graphdb/home/data/repositories/WeVerify/config.ttl
      - type: bind
        source: ./search/vera.pie
        target: /opt/graphdb/home/data/repositories/WeVerify/vera.pie
      - type: bind
        source: $HOME/.ontotext/licenses/graphdb-ee.license
        target: /opt/graphdb/home/conf/graphdb.license
      - type: bind
        source: ./data
        target: /opt/graphdb/home/data